# Generated by Django 4.2 on 2023-04-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='clothes', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='image',
            field=models.ImageField(upload_to='prompts', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='result',
            name='image',
            field=models.ImageField(upload_to='results', verbose_name='Изображение'),
        ),
    ]
