# Generated by Django 4.2 on 2023-06-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='image',
        ),
        migrations.AddField(
            model_name='style',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='clothes', verbose_name='Иконка'),
        ),
        migrations.DeleteModel(
            name='ClothesPrompt',
        ),
    ]
