# Generated by Django 4.2 on 2023-04-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='image',
        ),
        migrations.RemoveField(
            model_name='style',
            name='alias',
        ),
    ]
