# Generated by Django 4.2 on 2023-04-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_clothing_icon_alter_prompt_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='error',
            field=models.TextField(blank=True, editable=False, verbose_name='Ошибка'),
        ),
    ]
