# Generated by Django 4.2 on 2023-05-12 10:30

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_prompt_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='clothes',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='colorscheme',
        ),
        migrations.CreateModel(
            name='ClothesPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Цвет')),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clothing', verbose_name='Одежда')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='app.prompt', verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Запрос одежды',
                'verbose_name_plural': 'Запросы одежды',
            },
        ),
    ]
