# Generated by Django 4.2 on 2023-05-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_prompt_clothes_remove_prompt_colorscheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='clothes',
            field=models.ManyToManyField(blank=True, to='app.clothing', verbose_name='Одежда'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='colorscheme',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цветовая гамма'),
        ),
        migrations.DeleteModel(
            name='ClothesPrompt',
        ),
    ]
